### ISSUE TITLE
Neoloader can add wrong hash.

### ISSUE THREAD

**Issue by enOehTsIsihT** [NeoLoader/NeoLoader#11]
magnet:?xt=urn:btih:CB84CCC10F296DF72D6C40BA7A07C178A4323A1
magnet:?xt=urn:btih:CB84CCC10F296DF72D6C40BA7A07C178A4323A14

clip0081.7z 607 KB
https://mega.co.nz/#!tkUFQJKD!GtFho4e63u9aoRKcMQd-Eb0mJhzIy6Wt6PWrDAN_vkc

**Comment by DavidXanatos** [comment]
fixed
