### ISSUE TITLE
Ipfilter list's service support

### ISSUE THREAD

**Issue by obtim** [NeoLoader/NeoLoader#23]
Please, add support for Please, add support for https://www.iblocklist.com/lists.php?category=general&fileformat=p2p&archiveformat=zip  service of lists service of ipfilter lists.

**Comment by DavidXanatos** [comment]
This feature was present in the past but due to practical considerations was removed,
It does not protect you from any real threads it just a placebo.
if you want to dispute that assertion you can post in forum.
