### ISSUE TITLE
progress bug

### ISSUE THREAD

**Issue by enOehTsIsihT** [NeoLoader/NeoLoader#6]
clip0047.7z 54 KB
https://mega.co.nz/#!JsFniLqB!d4fbEs5xd4iUcxIT41I2xaXTHVnYh3aPUYjRrSAG_rs
clip0048.7z 41 KB
https://mega.co.nz/#!p9cBCKAQ!FaCRacaZ6FcehSBDgvvLVX3cAiCOR71g6DnRKTZCwug

magnet:?xt=urn:btih:0a5425b286dd4a0a385fd0db13320ac5cdb5deaf

**Comment by DavidXanatos** [comment]
fixed in next beta
